export enum Game {
  DEFAULT = 'DEFAULT',
  FAST_CLICK = 'FAST_CLICK',
  ROULETTE = 'ROULETTE',
  COIN_TOSS = 'COIN_TOSS',
  CROCODILIA = 'CROCODILIA',
}

export enum GameProgress {
  USER_LIST = 'USER_LIST',
  INIT_SCREEN = 'INIT_SCREEN',
  WAIT = 'WAIT',
  PLAY_GAME = 'PLAY_GAME',
  RESULT = 'RESULT',
}
